//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Content_Management_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_EVENT
    {
        public decimal EVENT_ID { get; set; }
        public System.Guid EVENT_GUID { get; set; }
        public Nullable<System.Guid> TYPE_GUID { get; set; }
        public Nullable<System.Guid> PLACE_GUID { get; set; }
        public Nullable<System.Guid> CATEGORY_GUID { get; set; }
        public string EVENT_TITLE { get; set; }
        public string EVENT_DESC { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string DATE_TIME { get; set; }
        public string VENUE { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public string WEBSITE { get; set; }
        public string AGE_RESTRICTION { get; set; }
        public string COST { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public string CONTACT_PHONE { get; set; }
        public string EXTERNAL_EVENT_ID { get; set; }
        public System.Guid ENTERED_BY { get; set; }
        public System.DateTime ENTERED_DATE_TIME { get; set; }
        public Nullable<System.Guid> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE_TIME { get; set; }
        public Nullable<System.Guid> DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_DATE_TIME { get; set; }
    }
}
