//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Content_Management_Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_MEDIA
    {
        public decimal MEDIA_ID { get; set; }
        public System.Guid MEDIA_GUID { get; set; }
        public Nullable<System.Guid> MEDIA_TYPE_GUID { get; set; }
        public string MEDIA_TITLE { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> PALETTE_BACKGROUND { get; set; }
        public Nullable<decimal> PALETTE_TEXT { get; set; }
        public System.Guid ENTERED_BY { get; set; }
        public System.DateTime ENTERED_DATE_TIME { get; set; }
        public Nullable<System.Guid> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE_TIME { get; set; }
        public Nullable<System.Guid> DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_DATE_TIME { get; set; }
    }
}
