//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Content_Management_Editor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelContentManagerEntities : DbContext
    {
        public TravelContentManagerEntities()
            : base("name=TravelContentManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuildVersion> BuildVersions { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TOUR> TOURs { get; set; }
        public virtual DbSet<TOUR_CATEGORY> TOUR_CATEGORY { get; set; }
        public virtual DbSet<TOUR_EVENT> TOUR_EVENT { get; set; }
        public virtual DbSet<TOUR_MEDIA> TOUR_MEDIA { get; set; }
        public virtual DbSet<TOUR_MEDIA_TO_ITEM> TOUR_MEDIA_TO_ITEM { get; set; }
        public virtual DbSet<TOUR_ORGANIZATION> TOUR_ORGANIZATION { get; set; }
        public virtual DbSet<TOUR_ORGANIZATION_TO_ITEM> TOUR_ORGANIZATION_TO_ITEM { get; set; }
        public virtual DbSet<TOUR_PATH> TOUR_PATH { get; set; }
        public virtual DbSet<TOUR_PLACE> TOUR_PLACE { get; set; }
        public virtual DbSet<TOUR_PLACE_TO_CATEGORY> TOUR_PLACE_TO_CATEGORY { get; set; }
        public virtual DbSet<TOUR_PLACE_TO_TOUR> TOUR_PLACE_TO_TOUR { get; set; }
        public virtual DbSet<TOUR_TO_CATEGORY> TOUR_TO_CATEGORY { get; set; }
        public virtual DbSet<TOUR_TYPE> TOUR_TYPE { get; set; }
    }
}
